#!/usr/bin/python

import json
import genericrequest


TEST1 = {'color1': '#68228B', 'height': '700', 'width': '500', 'contrast': '100', 'hue': '134', 'saturation': '100', 'format': 'gif', 'stripes': 'true', 'halftone': 'smallerdots1', 'burriness': '13', 'color2': '#000000', 'gradienttype': 'radial', 'bevel': 'evenlyframed', 'rotate': '99', 'percentbeveled': '40', 'name': 'richard_giovanni', 'brightness': '130', 'flop': 'true', 'flip': 'true', 'stripenumber': '3', 'stripeintensity': '748'}
json.dumps(TEST1)

genericrequest.request("http://asdf.us/cgi-bin/im/gradient", TEST1)
