USERNAME = "RICHARD_GIOVANNI"
TEST_URL = "http://i.asdf.us/im/fc/imBreak5qI6DN2_1425433157_.png"
PATTERN_BASE_URL = "http://asdf.us/impattern/patterns"
IMPATTERN_URL = "http://asdf.us/im/api/impattern"
IMGRID_URL = "http://asdf.us/im/api/imgrid"
IMGRADIENT_URL = "http://asdf.us/im/api/imgradient"
IMBREAK_URL = "http://asdf.us/im/api/imbreak"
